# For details see https://documenteer.lsst.io/guides/toml-reference.html

[project]
title = "Rubin Data Facilities"
copyright = "2025"
base_url = "https://df-ops.lsst.io"
github_url = "https://github.com/lsst/df-ops"
version = "Current"

[sphinx]
rst_epilog_file = "rst_epilog.rst"

[sphinx.linkcheck]
ignore = [
    "^http://localhost",
    "^http(s)*://ls.st",
    "https://slactraining.skillport.com/skillportfe/login.action",
    "^https://www-internal.slac.stanford.edu",
    "^https://k8s.slac.stanford.edu",
    "^https://confluence.lsstcorp.org",
    "^https://s3dfnx.slac.stanford.edu",
    "^https://s3df.slac.stanford.edu",
    "^https://usdf-rsp.slac.stanford.edu",
    "^https://github.com",
]